name: Run Google Colab Script Daily

on:
  workflow_dispatch:  # Enables manual trigger from GitHub UI
  schedule:
    - cron: '0 8 * * *'  # Runs daily at 8 AM UTC

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run the Python Script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          INPUT_SPREADSHEET_URL: ${{ secrets.INPUT_SPREADSHEET_URL }}
          INPUT_WORKSHEET_NAME: ${{ secrets.INPUT_WORKSHEET_NAME }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
        run: |
          echo "$GOOGLE_CREDENTIALS" > credentials.json
          python __init__.py
